### ISSUE TITLE
Heroku server crashes - NameError: uninitialized constant YAML

### ISSUE THREAD

**Issue by justinhartman** [justinhartman/jekyll-heroku-starter-kit#2]
### Describe the Bug

When trying to access the built Heroku site [over here](https://jekyll-heroku-starter-kit.herokuapp.com) there is an Application error message:

![2020-07-09 at 10 19 25][screenshot-1]

Running `heroku logs --tail` shows the following output:

```log
2020-07-09T07:03:51.351930+00:00 heroku[web.1]: State changed from crashed to starting
2020-07-09T07:03:56.929879+00:00 heroku[web.1]: Starting process with command `bundle exec rackup config.ru -p 4413`
2020-07-09T07:04:01.760002+00:00 app[web.1]: [heroku-exec] Starting
2020-07-09T07:04:03.238895+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-jekyll-0.3.5/lib/rack/jekyll.rb:60: warning: key "Content-Type" is duplicated and overwritten on line 60
2020-07-09T07:04:03.318686+00:00 app[web.1]: bundler: failed to load command: rackup (/app/vendor/bundle/ruby/2.6.0/bin/rackup)
2020-07-09T07:04:03.323469+00:00 app[web.1]: NameError: uninitialized constant YAML
2020-07-09T07:04:03.323471+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-jekyll-0.3.5/lib/rack/jekyll.rb:10:in `initialize'
2020-07-09T07:04:03.323472+00:00 app[web.1]: /app/config.ru:2:in `new'
2020-07-09T07:04:03.323472+00:00 app[web.1]: /app/config.ru:2:in `block in <main>'
2020-07-09T07:04:03.323472+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
2020-07-09T07:04:03.323473+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
2020-07-09T07:04:03.323473+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
2020-07-09T07:04:03.323474+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
2020-07-09T07:04:03.323475+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
2020-07-09T07:04:03.323476+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
2020-07-09T07:04:03.323476+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
2020-07-09T07:04:03.323477+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
2020-07-09T07:04:03.323477+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
2020-07-09T07:04:03.323478+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
2020-07-09T07:04:03.323478+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
2020-07-09T07:04:03.323478+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
2020-07-09T07:04:03.323479+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `load'
2020-07-09T07:04:03.323480+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `<top (required)>'
2020-07-09T07:04:03.404037+00:00 heroku[web.1]: Process exited with status 1
2020-07-09T07:04:03.460298+00:00 heroku[web.1]: State changed from starting to crashed
```

### Additional Context

This has to be caused by the recent upgrade from Jekyll 3 to 4. The last successful deploy to Heroku was commit 07b8c9a2 on 7 July. The next push to Heroku was commit 3113e619 on 9 July and since then the server has been crashing.

```log
2020-07-09T00:59:17.000000+00:00 app[api]: Build started by user iamjustinhartman@gmail.com
2020-07-09T01:02:53.117818+00:00 app[api]: Deploy 3113e619 by user iamjustinhartman@gmail.com
2020-07-09T01:02:53.117818+00:00 app[api]: Release v30 created by user iamjustinhartman@gmail.com
2020-07-09T01:02:53.289775+00:00 heroku[web.1]: Restarting
2020-07-09T01:02:53.304177+00:00 heroku[web.1]: State changed from up to starting
2020-07-09T01:02:54.651311+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-07-09T01:02:54.710909+00:00 app[web.1]: [2020-07-09 03:02:54] FATAL SignalException: SIGTERM
2020-07-09T01:02:54.710919+00:00 app[web.1]: /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/webrick/server.rb:170:in `select'
2020-07-09T01:02:54.710920+00:00 app[web.1]: /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/webrick/server.rb:170:in `block in start'
2020-07-09T01:02:54.710920+00:00 app[web.1]: /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/webrick/server.rb:32:in `start'
2020-07-09T01:02:54.710921+00:00 app[web.1]: /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/webrick/server.rb:157:in `start'
2020-07-09T01:02:54.710921+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-1.6.13/lib/rack/handler/webrick.rb:34:in `run'
2020-07-09T01:02:54.710922+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-1.6.13/lib/rack/server.rb:287:in `start'
2020-07-09T01:02:54.710922+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-1.6.13/lib/rack/server.rb:148:in `start'
2020-07-09T01:02:54.710922+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-1.6.13/bin/rackup:4:in `<top (required)>'
2020-07-09T01:02:54.710923+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `load'
2020-07-09T01:02:54.710923+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `<top (required)>'
2020-07-09T01:02:54.710924+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
2020-07-09T01:02:54.710924+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
2020-07-09T01:02:54.710924+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
2020-07-09T01:02:54.710925+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
2020-07-09T01:02:54.710926+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2020-07-09T01:02:54.710927+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2020-07-09T01:02:54.710927+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
2020-07-09T01:02:54.710928+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
2020-07-09T01:02:54.710928+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
2020-07-09T01:02:54.710928+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
2020-07-09T01:02:54.710929+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
2020-07-09T01:02:54.710929+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
2020-07-09T01:02:54.710929+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
2020-07-09T01:02:54.710931+00:00 app[web.1]: /app/vendor/bundle/bin/bundle:104:in `load'
2020-07-09T01:02:54.710931+00:00 app[web.1]: /app/vendor/bundle/bin/bundle:104:in `<main>'
2020-07-09T01:02:54.711276+00:00 app[web.1]: [2020-07-09 03:02:54] INFO  going to shutdown ...
2020-07-09T01:02:54.711376+00:00 app[web.1]: [2020-07-09 03:02:54] INFO  WEBrick::HTTPServer#start done.
2020-07-09T01:02:54.724813+00:00 app[web.1]: Configuration file: /app/_config.yml
2020-07-09T01:02:54.811474+00:00 heroku[web.1]: Process exited with status 143
2020-07-09T01:02:56.388178+00:00 heroku[web.1]: Starting process with command `bundle exec rackup config.ru -p 47042`
2020-07-09T01:02:58.000000+00:00 app[api]: Build succeeded
2020-07-09T01:02:58.605495+00:00 app[web.1]: [heroku-exec] Starting
2020-07-09T01:02:58.914201+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-jekyll-0.3.5/lib/rack/jekyll.rb:60: warning: key "Content-Type" is duplicated and overwritten on line 60
2020-07-09T01:02:58.933916+00:00 app[web.1]: bundler: failed to load command: rackup (/app/vendor/bundle/ruby/2.6.0/bin/rackup)
2020-07-09T01:02:58.935083+00:00 app[web.1]: NameError: uninitialized constant YAML
2020-07-09T01:02:58.935084+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-jekyll-0.3.5/lib/rack/jekyll.rb:10:in `initialize'
2020-07-09T01:02:58.935084+00:00 app[web.1]: /app/config.ru:2:in `new'
2020-07-09T01:02:58.935085+00:00 app[web.1]: /app/config.ru:2:in `block in <main>'
2020-07-09T01:02:58.935085+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
2020-07-09T01:02:58.935086+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
2020-07-09T01:02:58.935086+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
2020-07-09T01:02:58.935086+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
2020-07-09T01:02:58.935087+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
2020-07-09T01:02:58.935088+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
2020-07-09T01:02:58.935088+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
2020-07-09T01:02:58.935089+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
2020-07-09T01:02:58.935089+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
2020-07-09T01:02:58.935089+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
2020-07-09T01:02:58.935090+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:168:in `start'
2020-07-09T01:02:58.935090+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/bin/rackup:5:in `<top (required)>'
2020-07-09T01:02:58.935091+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `load'
2020-07-09T01:02:58.935091+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/bin/rackup:23:in `<top (required)>'
2020-07-09T01:02:58.987020+00:00 heroku[web.1]: Process exited with status 1
2020-07-09T01:02:59.022414+00:00 heroku[web.1]: State changed from starting to crashed
```

[//]: # (Add links to any screenshots or other relevant information below)

[screenshot-1]: https://user-images.githubusercontent.com/717118/87015435-b5286000-c1cd-11ea-87f0-91b1307e2027.png

**Comment by justinhartman** [comment]
The reason this is happening is that `rack-jekyll` is trying to load the `/app/_config.yml` file but this no longer works since the upgrade. The way to fix it is to add `require 'yaml'` to your Rack configuration file. This ensures Rack loads the `yaml` module before `rack-jekyll` tries to load the Jekyll configuration file.

Commit 67522d0 closes this issue.
